apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: simple-crud
  name: simple-crud
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: simple-crud
  type: NodePort
status:
  loadBalancer: {}
