apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: secret
            key: admin
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secret
            key: daca2019
  restartPolicy: Never